"""Add exercise assignments

Revision ID: c45576811ab9
Revises: a257861e9f06
Create Date: 2026-09-01 10:43:13.983605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45576811ab9'
down_revision = 'a257861e9f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_assignments_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_assignments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_assignments_therapist_id'), ['therapist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_assignments_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_assignments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_assignments_exercise_id'))

    op.drop_table('exercise_assignments')
    # ### end Alembic commands ###
