"""Initial database schema

Revision ID: f63de1f0af26
Revises: 
Create Date: 2026-08-26 21:10:09.750842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63de1f0af26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_area', sa.String(length=120), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('rehabilitation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rehabilitation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rehabilitation_sessions_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rehabilitation_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rehabilitation_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_user_id'), ['user_id'], unique=False)

    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(length=100), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rehabilitation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_results_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_results_session_id'))

    op.drop_table('session_results')
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_progress_records_session_id'))

    op.drop_table('progress_records')
    with op.batch_alter_table('rehabilitation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rehabilitation_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_rehabilitation_sessions_exercise_id'))

    op.drop_table('rehabilitation_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
